// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8ifUfhyHGXIh3Y-wZfOhfwyJe_F0l4y8',
    appId: '1:340309557479:web:f3a797e3ce7a0c4e4f6242',
    messagingSenderId: '340309557479',
    projectId: 'quest-for-calculus',
    authDomain: 'quest-for-calculus.firebaseapp.com',
    storageBucket: 'quest-for-calculus.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcA2EGg5bKHdWc48u2VY7s2oQcIqhOYxQ',
    appId: '1:340309557479:android:a0743eef64b6b4de4f6242',
    messagingSenderId: '340309557479',
    projectId: 'quest-for-calculus',
    storageBucket: 'quest-for-calculus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpvrvOV-Q8mHeyLRzkVv3DfL5Bz7Y6C1A',
    appId: '1:340309557479:ios:afc66a63b6a010be4f6242',
    messagingSenderId: '340309557479',
    projectId: 'quest-for-calculus',
    storageBucket: 'quest-for-calculus.appspot.com',
    iosBundleId: 'com.example.questForCalculus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpvrvOV-Q8mHeyLRzkVv3DfL5Bz7Y6C1A',
    appId: '1:340309557479:ios:cbad5d2607c80f7e4f6242',
    messagingSenderId: '340309557479',
    projectId: 'quest-for-calculus',
    storageBucket: 'quest-for-calculus.appspot.com',
    iosBundleId: 'com.example.questForCalculus.RunnerTests',
  );
}
